---
title: "workspace"
output: html_notebook
---

```{r}
# load libraries
library(tidyverse)
library(caret)
library(ggplot2)
library(corrplot)
library(dplyr)
# load data

train <- read.csv("playground-series-s6e3/train.csv")
test  <- read.csv("playground-series-s6e3/test.csv")

# target variable is called Churn
```

## LOOK AT DATA

```{r}
head(train) 
names(train) # column names
```

```{r}
sum(is.na(train))  # no na values
sum(is.na(test))  # no na values
```

```{r}
# summary of data
summary(train)
```

```{r}
# range of vals for numerical cols
numeric_cols <- names(train)[sapply(train, is.numeric)]
numeric_cols <- setdiff(numeric_cols, "id")

range_compare <- data.frame(
  feature = numeric_cols,
  train_min = sapply(train[numeric_cols], min),
  train_max = sapply(train[numeric_cols], max),
  test_min  = sapply(test[numeric_cols], min),
  test_max  = sapply(test[numeric_cols], max)
)

print(range_compare)
```

```{r}
# see values for cat cols
## see which we have to make 0/1 and which to one
# hot encode

cat_cols <- names(train)[sapply(train, is.character)]

for(col in cat_cols){

  cat("\n====================\n")
  cat("Column:", col, "\n")

  cat("\nTrain values:\n")
  print(unique(train[[col]]))

  cat("\nTest values:\n")
  print(unique(test[[col]]))

}
```

## DATA CLEANING

```{r}
# make yes/no cols into binary cols

train <- train |>
  mutate(
    gender = ifelse(gender == "Male", 1, 0),
    Partner = ifelse(Partner == "Yes", 1, 0),
    Dependents = ifelse(Dependents == "Yes", 1, 0),
    PhoneService = ifelse(PhoneService == "Yes", 1, 0),
    PaperlessBilling = ifelse(PaperlessBilling == "Yes", 1, 0),
    Churn = ifelse(Churn == "Yes", 1, 0)
  )

test <- test |>
  mutate(
    gender = ifelse(gender == "Male", 1, 0), 
    Partner = ifelse(Partner == "Yes", 1, 0),
    Dependents = ifelse(Dependents == "Yes", 1, 0),
    PhoneService = ifelse(PhoneService == "Yes", 1, 0),
    PaperlessBilling = ifelse(PaperlessBilling == "Yes", 1, 0)
  )
```


```{r}
# one hot encode the rest of the variables

train <- train |>
  mutate(
    MultipleLines = as.factor(MultipleLines),
    InternetService = as.factor(InternetService),
    OnlineSecurity = as.factor(OnlineSecurity),
    OnlineBackup = as.factor(OnlineBackup),
    DeviceProtection = as.factor(DeviceProtection),
    TechSupport = as.factor(TechSupport),
    StreamingTV = as.factor(StreamingTV),
    StreamingMovies = as.factor(StreamingMovies),
    Contract = as.factor(Contract),
    PaymentMethod = as.factor(PaymentMethod)
  )

test <- test |>
  mutate(
    MultipleLines = as.factor(MultipleLines),
    InternetService = as.factor(InternetService),
    OnlineSecurity = as.factor(OnlineSecurity),
    OnlineBackup = as.factor(OnlineBackup),
    DeviceProtection = as.factor(DeviceProtection),
    TechSupport = as.factor(TechSupport),
    StreamingTV = as.factor(StreamingTV),
    StreamingMovies = as.factor(StreamingMovies),
    Contract = as.factor(Contract),
    PaymentMethod = as.factor(PaymentMethod)
  )
```

```{r}
numeric_cols <- names(train)[sapply(train, is.numeric)] # numerical cols
numeric_cols <- setdiff(numeric_cols, c("id", "Churn"))

preproc <- preProcess(train[, numeric_cols], method = c("center", "scale")) # scalar

train_scaled <- train # scale train
train_scaled[, numeric_cols] <- predict(preproc, train[, numeric_cols])
test_scaled <- test # scale test
test_scaled[, numeric_cols] <- predict(preproc, test[, numeric_cols])
```

```{r}
matrix <- cor(train_scaled[numeric_cols])
corrplot(matrix, method = "color")
```


```{r}
summary(train_scaled) # mean 0
# data is imbalanced, mean of churn 0.22 so we may have to bootstrap or be careful with results
```
```{r}

```


```{r}
# dont need id and get rid of churn for training
x_train <- train_scaled %>% select(-id, -Churn)
y_train <- train_scaled$Churn
x_test <- test_scaled %>% select(-id)

# one-hot encode to numerical values valid for model
x_train <- model.matrix(~ . -1, data = x_train)
x_test  <- model.matrix(~ . -1, data = x_test)
```


```{r}
dim(x_train)
dim(y_train)
```

```{r}
# logistic regression
log_model <- glm(
  y_train ~ .,
  data = as.data.frame(x_train),
  family = "binomial"
)

# Predict probabilities
log_preds <- predict(
  log_model,
  newdata = as.data.frame(x_test),
  type = "response"
)

# Save results
log_results <- data.frame(
  id = test$id,
  Churn = log_preds
)

write.csv(log_results, "results_logistic.csv", row.names = FALSE)
```

```{r}
library(randomForest)
y_train_yn <- factor(y_train, levels = c(0, 1), labels = c("No", "Yes"))
# Train model
rf_model <- randomForest(
  x = x_train,
  y = y_train_yn,
  ntree = 100,
  mtry = floor(sqrt(ncol(x_train))),
  do.trace = 10
)

# Predict probabilities (class "Yes")
rf_preds <- predict(rf_model, x_test, type = "prob")[, "Yes"]

# Save results
rf_results <- data.frame(
  id = test$id,
  Churn = rf_preds
)

write.csv(rf_results, "results_randomforest.csv", row.names = FALSE)
```

```{r}

```


```{r}
library(xgboost)

# Create DMatrix
dtrain <- xgb.DMatrix(data = x_train, label = y_train)
dtest  <- xgb.DMatrix(data = x_test)

# hyperparameters we can gridsearch/randomsearch
# max_depth
# learning_rate
# objective
# max_leaves
# min_split
# gamma

# Train model
xgb_model <- xgboost(
  data = dtrain,
  nrounds = 100,
  objective = "binary:logistic",
  eval_metric = "logloss",
  max_depth = 6,
  eta = 0.1,
  verbose = 1
)

# Predict probabilities
xgb_preds <- predict(xgb_model, dtest)

# Save results
xgb_results <- data.frame(
  id = test$id,
  Churn = xgb_preds
)

write.csv(xgb_results, "results_xgboost.csv", row.names = FALSE)
```




